pdf_path: "C:/Users/prakh/Downloads/casestudy/code/final/data/Request 2.pdf"
output_excel_path: "C:/Users/prakh/Downloads/casestudy/code/final/query2.xlsx"
openai_model: "gpt-4o"
temperature_pdf_2_text: 0.6
system_message_pdf_2_text: |
  You are an expert in extracting item details from text. Extract the item details for every item in a structured markdown table format with columns 'Item Name and Description' and 'Quantity'. The output should be in the following format:

  | Item Name and Description | Quantity |
  |---------------------------|----------|
  | Example Item 1            | 12345    |
  | Example Item 2            | 67890    |.

  You have to only give the item details without any description of what it is.

system_message_category_dimension: |
  You are an expert in identifying the product category and its dimension from the item details. The category should only be one of the following: 'Stud', 'Track', 'Clip', 'Strap'. If you think it is something else then you should leave it empty. The dimensions in this example - [135820] 3-5/8 a Track, 10' are 3-5/8 and not 10' and in this example - 10' x 2' x 16ga Ext Stud, 18' (S1000S200-54) is 10IN 2IN. Remember this pattern. Provide the answer in the format: 'Dimension: <dimension>, Category: <category>'. If you are not able to identify something do not write anything.
temperature_category_dimension: 0.6
updated_excel_path: "C:/Users/prakh/Downloads/casestudy/code/final/updated_query2.xlsx"

database_path: "C:/Users/prakh/Downloads/casestudy/code/final/data/ProductDB.csv"
final_output_excel_path: "C:/Users/prakh/Downloads/casestudy/code/final/results/mapping_request_2/after_mapping.xlsx"
database_column_index: 2
fuzzy_match_threshold: 70

